name = "agent-ads"
main = "src/index.ts"
compatibility_date = "2025-10-08"

[observability]
enabled = true

[vars]
PAY_TO = "0x8BEBC14028D896a7b323544bfc49F24cdcD63CA7"
PAYMENT_CURRENCY = "0x20C000000000000000000000b9537d11c60E8b50"
TEMPO_TESTNET = false

[[r2_buckets]]
binding = "AD_BUCKET"
bucket_name = "agent-ads"

[[d1_databases]]
binding = "DB"
database_name = "agent-ads-db"
database_id = "640d225c-d13c-4b8b-bafe-b6bd4dae2977"
